### ISSUE TITLE
DeploymentConfig not deleted when undeploy stream

### ISSUE THREAD

**Issue by tobiasdenzler** [donovanmuller/spring-cloud-deployer-openshift#32]
After clicking Undeploy in the Streams tab the stream should be undeployed and completely removed. But the DeploymentConfig and its corresponding ReplicationController will never be deleted. This can be reproduced always.

We tracked down the problem to the _undeploy(String addId)_ method and the _client.deploymentConfigs().withName(deploymentConfig.getMetadata().getName()).scale(0, true)_. It seems that the client waits for a default timeout of 600 seconds and then silently disappears (at least it seems that does not do anything after this point).

Are you familiar with such a behaviour? We use OpenShift 3.2 with Kubernetes 1.2.

**Comment by donovanmuller** [comment]
This could be related to OpenShift 3.2, as I have only thoroughly tested the `1.1.0.RELEASE` with OpenShift Origin 1.3. I'll have to try and reproduce this with Origin 1.2...

I do seem to remember some differences in the cascading deletion of resources from 1.2.
Given that you are currently using 3.2, a PR to fix this would be much appreciated (however, I will try and reproduce as soon as I have some time).

**Comment by tobiasdenzler** [comment]
We moved to OpenShift Container Platform 3.3 and the issue cannot be reproduced there anymore.
