### ISSUE TITLE
Not able to pass custom spring.cloud.deployer.kubernetes.serviceAnnotations property

### ISSUE THREAD

**Issue by ravindrabhatt** [donovanmuller/spring-cloud-deployer-openshift#45]
stream deploy --name streamName --properties "app.custom.spring.cloud.deployer.openshift.serviceAnnotations=name:value"
OR
task launch --name --properties "app.custom.spring.cloud.deployer.openshift.serviceAnnotations=name:value"

does not add the name->value entry under annotations tag of deployment config of app even though kubernetes deployer supports it .

Event tried "app.custom.spring.cloud.deployer.kubernetes.serviceAnnotations=name:value"

See getAnnotations method at https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java

**Comment by donovanmuller** [comment]
Thanks for the crating the issue 👍 

The support for Service annotations was added in `1.2.2.RELEASE` of [spring-cloud-deployer-kubernetes](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/bebd4addedaffe40a1f04fafcddeba3528c632e4).

The current version used by this OpenShift deployer is `1.2.1.RELEASE` and hence your issue.

I will update to the `1.2.2.RELEASE` of `spring-cloud-deployer-kubernetes` and release `1.2.1.RELEASE` as soon as I can (#44).

**Comment by ravindrabhatt** [comment]
Is there also a way to add pod level spec annotations?

We want to add an initContainer to the pod that gets deployed as part of stream pipeline, is it possible with current openshift deployer?

**Comment by donovanmuller** [comment]
There is currently no support for [Init Containers](https://docs.openshift.com/container-platform/3.6/architecture/core_concepts/containers_and_images.html#init-containers) in the OpenShift deployer.

I have created a separate issue to investigate adding this.

**Comment by ravindrabhatt** [comment]
Ok Thanks

**Comment by donovanmuller** [comment]
@ravindrabhatt I have released [1.2.1.RELEASE](https://github.com/donovanmuller/spring-cloud-deployer-openshift/releases/tag/v1.2.1.RELEASE) with `1.2.2.RELEASE` of `spring-cloud-deployer-kubernetes`.

You should now have the ability to pass `app.custom.spring.cloud.deployer.openshift.serviceAnnotation` deployment properties.
Can you please test and verify that this is resolved?
