### ISSUE TITLE
Duplicate KubernetesDeployerProperties

### ISSUE THREAD

**Issue by kalvarez2** [donovanmuller/spring-cloud-deployer-openshift#52]
Tried to use as a dependency in my project. Just added a REST controller to expose the AppDeployer API as REST entry points, when the application boots I get : 
```
Field properties in org.springframework.cloud.deployer.spi.kubernetes.KubernetesAutoConfiguration required a single bean, but 2 were found:
	- spring.cloud.deployer.kubernetes-org.springframework.cloud.deployer.spi.kubernetes.KubernetesDeployerProperties: defined in null
	- spring.cloud.deployer.openshift-org.springframework.cloud.deployer.spi.openshift.OpenShiftDeployerProperties: defined in null
```
I am using version 1.3.0.BUILD-SNAPSHOT:
```

                <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-deployer-openshift</artifactId>
			<version>1.3.0.BUILD-SNAPSHOT</version>
		</dependency>
```
and my parent pom points to:
```
       <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.8.RELEASE</version>
		<relativePath />
	</parent>
```

**Comment by donovanmuller** [comment]
Hi @kalvarez2!

Thanks for the feedback.
You have to exclude `KubernetesAutoConfiguration` in your application.

See the [Spring Cloud Data Flow Server](https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift/blob/8d51169437b07aaae79988a342ff2cae29cef652/spring-cloud-dataflow-server-openshift/src/main/java/org/springframework/cloud/dataflow/server/openshift/OpenShiftDataFlowServer.java#L13) for an example:

```java
@SpringBootApplication(exclude = KubernetesAutoConfiguration.class)
@EnableDataFlowServer
public class OpenShiftDataFlowServer {

    public static void main(String[] args) {
        SpringApplication.run(OpenShiftDataFlowServer.class, args);
    }
}
```

**Comment by kalvarez2** [comment]
Thanks! that solves it. Interestingly, even after excluding it was showing up duplicate, because I had a @EnableAutoConfiguration like this:
```

@SpringBootApplication(exclude = KubernetesAutoConfiguration.class)
@EnableAutoConfiguration
public class MyApplication {
	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}
}
```
thanks again!

**Comment by donovanmuller** [comment]
If you use `@SpringBootApplication` it already uses `@EnableAutoConfiguration`. Using it again causes conflicts. See https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-using-springbootapplication-annotation.html

**Comment by kalvarez2** [comment]
I really have no idea why I had it there...
